### ISSUE TITLE
ImportError: No module named cfaidx

### ISSUE THREAD

**Issue by mingyi-wang** [kylessmith/SomVarIUS#2]
I've installed the SomVarIUS and pysam is also included in python. But when I ran "SomVarIUS -h", I got the error likes followings. Could you let me know how to fix that?

Traceback (most recent call last):
  File "/DCEG/Resources/Tools/python/2.7.8-shared/bin/SomVarIUS", line 4, in <module>
    __import__('pkg_resources').run_script('SomVarIUS==1.2', 'SomVarIUS')
  File "/DCEG/Resources/Tools/python/2.7.8-shared/lib/python2.7/site-packages/pkg_resources/__init__.py", line 746, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/DCEG/Resources/Tools/python/2.7.8-shared/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1508, in run_script
    exec(script_code, namespace, namespace)
  File "/DCEG/Resources/Tools/python/2.7.8-shared/lib/python2.7/site-packages/SomVarIUS-1.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/SomVarIUS", line 3, in <module>
    __requires__ = 'SomVarIUS==1.2'
  File "build/bdist.linux-x86_64/egg/SomVarIUS_calling.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/SomVarIUS_calling.py", line 6, in __bootstrap__
  File "cfaidx.pxd", line 40, in init SomVarIUS_calling (SomVarIUS/SomVarIUS_calling.c:25100)
ImportError: No module named cfaidx

**Comment by kylessmith** [comment]
cfaidx.pxd is from pysam. However, it looks like the newest version renamed the modules. You can download an older version of pysam, but I will update the files by tomorrow morning.

**Comment by mingyi-wang** [comment]
I cannot install an older version of pysam because our python shared by other users. Could you update the files? Thanks!

**Comment by kylessmith** [comment]
The files should be up to date now

**Comment by mingyi-wang** [comment]
Now, we got compile errors for installation:
# pip install SomVarIUS
Downloading/unpacking SomVarIUS
  Downloading SomVarIUS-1.1.tar.gz (179kB): 179kB downloaded
  Running setup.py (path:/tmp/pip_build_root/SomVarIUS/setup.py) egg_info for package SomVarIUS
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/SomVarIUS/setup.py", line 42, in <module>
        ext_modules=cythonize(extensions),
      File "/DCEG/Resources/Tools/python/2.7.8-shared/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 799, in cythonize
        aliases=aliases)
      File "/DCEG/Resources/Tools/python/2.7.8-shared/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 691, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/DCEG/Resources/Tools/python/2.7.8-shared/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 107, in nonempty
        raise ValueError(error_msg)
    ValueError: 'SomVarIUS/SomVarIUS_calling.pyx' doesn't match any files
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/SomVarIUS/setup.py", line 42, in <module>

    ext_modules=cythonize(extensions),

  File "/DCEG/Resources/Tools/python/2.7.8-shared/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 799, in cythonize

    aliases=aliases)

  File "/DCEG/Resources/Tools/python/2.7.8-shared/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 691, in create_extension_list

    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):

  File "/DCEG/Resources/Tools/python/2.7.8-shared/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 107, in nonempty

    raise ValueError(error_msg)

ValueError: 'SomVarIUS/SomVarIUS_calling.pyx' doesn't match any files

**Comment by kylessmith** [comment]
I will work on updating the pypi version. Currently the github version is the most up to date.
