### ISSUE TITLE
IndexError: list index out of range 

### ISSUE THREAD

**Issue by Varunachander** [kylessmith/SomVarIUS#6]
Hi,
I encountered an issue using Somvarius: 

storing chromosome/dbsnp intersection in memory...
Traceback (most recent call last):
  File "/hgsccl/next-gen/scratch/chander/software/bin/SomVarIUS", line 4, in <module>
    __import__('pkg_resources').run_script('SomVarIUS==1.2', 'SomVarIUS')
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 517, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1430, in run_script
  File "/hgsccl/next-gen/scratch/chander/software/lib/python2.7/site-packages/SomVarIUS-1.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/SomVarIUS", line 265, in <module>
    
  File "/hgsccl/next-gen/scratch/chander/software/lib/python2.7/site-packages/SomVarIUS-1.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/SomVarIUS", line 196, in get_mutations
    
  File "SomVarIUS_calling.pyx", line 597, in write_mutations (SomVarIUS/SomVarIUS_calling.c:11842)
  File "SomVarIUS_calling.pyx", line 328, in SomVarIUS_calling.filter_regions (SomVarIUS/SomVarIUS_calling.c:7614)
IndexError: list index out of range

Any thoughts what is going on?
Best,
Varuna

**Comment by pllittle** [comment]
Hi,

I didn't have trouble running somvarius without CNV input, but when I did run it with CNV input, I received the following error in the log output.

Traceback (most recent call last):
  File "/opt/conda/bin/SomVarIUS", line 4, in <module>
    __import__('pkg_resources').run_script('SomVarIUS==1.2', 'SomVarIUS')
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/opt/conda/lib/python2.7/site-packages/SomVarIUS-1.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/SomVarIUS", line 265, in <module>
    
  File "/opt/conda/lib/python2.7/site-packages/SomVarIUS-1.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/SomVarIUS", line 196, in get_mutations
    
  File "SomVarIUS/SomVarIUS_calling.pyx", line 586, in write_mutations
IndexError: list index out of range

Best,
Paul
