### ISSUE TITLE
ImportError:undefined symbol: bgzf_read

### ISSUE THREAD

**Issue by pamonlan** [kylessmith/SomVarIUS#7]
I've installed the SomVarIUS. But when I ran "SomVarIUS -h", I got the error likes followings. Could you let me know how to fix that?

(base) pamonlan@omen:~$ SomVarIUS -h
Traceback (most recent call last):
  File "/usr/local/bin/SomVarIUS", line 4, in <module>
    __import__('pkg_resources').run_script('SomVarIUS==1.2', 'SomVarIUS')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/SomVarIUS-1.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/SomVarIUS", line 3, in <module>
    __requires__ = 'SomVarIUS==1.2'
  File "build/bdist.linux-x86_64/egg/SomVarIUS_calling.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/SomVarIUS_calling.py", line 6, in __bootstrap__
ImportError: /home/pamonlan/.cache/Python-Eggs/SomVarIUS-1.2-py2.7-linux-x86_64.egg-tmp/SomVarIUS_calling.so: undefined symbol: bgzf_read

**Comment by fmazzarotto** [comment]
Hi,
I am also experiencing the same issue. When I run "SomVarIUS -h" I obtain the following:

Traceback (most recent call last):
  File "/home/francesco_mazzarotto/.local/bin/SomVarIUS", line 4, in <module>
    __import__('pkg_resources').run_script('SomVarIUS==1.2', 'SomVarIUS')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/home/francesco_mazzarotto/.local/lib/python2.7/site-packages/SomVarIUS-1.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/SomVarIUS", line 3, in <module>
    __requires__ = 'SomVarIUS==1.2'
  File "build/bdist.linux-x86_64/egg/SomVarIUS_calling.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/SomVarIUS_calling.py", line 6, in __bootstrap__
ImportError: /home/francesco_mazzarotto/.cache/Python-Eggs/SomVarIUS-1.2-py2.7-linux-x86_64.egg-tmp/SomVarIUS_calling.so: undefined symbol: bgzf_read

Is there a way around this? I am not an expert in Python itself, so I fear I may need some help here. Thanks very much
